Mellanox/network-operator-docs

.github/workflows/build.yaml

Add build check on PR

---

.github/workflows/build.yaml

HTLM generated during the build can be downloaded from the build artifacts.
Example of the build:
https://github.com/ykulazhenkov/network-operator-docs/actions/runs/8184371629?pr=1

Update GH actions to store generated HTML as build artifact

---

README.md
docs/advanced-configurations.rst
docs/customizations/helm.rst
docs/k8s-baremetal-ethernet.rst
docs/multi-network-pod.rst
repo.toml

- add  linkcheck target
- update README
- Fix some broken and redirection links
- Align all OpenShift links to point to latest

Add linkcheck target

---

.gitignore
docs/common/vars.rst
docs/platform-support.rst

Signed-off-by: killianmuldoon <cilliancapi@gmail.com>
Add the platform support page.

docs: Add platform support page

---

docs/getting-started-kubernetes.rst

missing new line cause `code-block` to render incorrectly

Fix format of upgrade note for parallel node

---

docs/getting-started-kubernetes.rst

We should not mix the namesapces in the documentation.

docs: use same namespace in getting-started docs

---

docs/getting-started-kubernetes.rst

This PR adds missing apiVersions to the `SriovNetworkNodePolicies` in the getting-started docs.

docs: add missing apiVersion to SriovNetworkNodePolicy

---

docs/getting-started-kubernetes.rst

Remove the instructions for installing the NicClusterPolicy through helm from the documentation and replace it with a two step process that involves applying the NicClusterPolicy directly using `kubectl`.
This feature [is deprecated and is going to be removed from the Network Operator helm chart in a future release](https://github.com/mellanox/network-operator/blob/d55b311ece00be89b545f62ed71dad12bc4b7087/deployment/network-operator/templates/NOTES.txt#L6-L12)

Remove helm NicClusterPolicy install from docs

---

docs/getting-started-kubernetes.rst

PR https://github.com/Mellanox/network-operator-docs/pull/66 missed some references

align network operator namespace to nvidia-network-operator

---

.gitignore
.helmdocsignore
Makefile
docs/customizations/helm.rst
templates/helm.rst.gotmpl

This PR is about automating the helm docs generation for a given helm chart version. It relies on [helm-docs](https://pkg.go.dev/github.com/norwoodj/helm-docs/pkg/helm).
A template is provided in order to generate `heml.rst`, the reStructuredText formatted doc. This template has access to all the metadata in the chart's `requirements.yaml`, and `Chart.yaml` as well as the `chart values`. The advantage here is that any changes to those special files in the chart or in the template itself, can automatically generate an up to date documentation.
**Note** As we want to avoid any manual action i.e. copy for the helm chart `values`, the `values.yaml` is the source of truth  and has to be update to contain all needed information. One critical missing part is the fields descriptions. We can also …

feat: Automate helm docs

---

Makefile
README.md

Add new makefile targets to enable this workflow
user should run:
`HELM_CHART_PATH=/path/to/network-operator/local/chart make local-helm-docs`
In addition perform some Makefile cleanup/maintenance

Add option to generate helm docs from local path

---

docs/customizations/helm.rst
docs/release-notes.rst
templates/helm.rst.gotmpl

if nvme driver is loaded in the host system doca driver container will fail if ENABLE_NFSRDMA is set to true.
document this limitation.

update docs with nvme storage modules limitations

---

.github/workflows/docs-ci.yaml

Note: This workflow shall be triggered from the https://github.com/Mellanox/network-operator repository ([additional PR](https://github.com/Mellanox/network-operator/pull/1045) there).

feat: add ci for making docs

---

Makefile
docs/customizations/helm.rst
templates/helm.rst.gotmpl

See https://github.com/Mellanox/network-operator/pull/1064

bug: fix object rendering in helm doc

---

docs/getting-started-kubernetes.rst

cniPlugins and multus are fields inside the secondaryNetwork block.

fix: examples for NicClusterPolicy

---

.github/workflows/docs-ci.yaml

Fixing failed (404 Not found) 'gh repo sync' since it was trying to fork 'network-operator' instead of 'network-operator-docs' repo
```
2024-11-03T08:13:23.6882567Z   GH_TOKEN: ***
2024-11-03T08:13:23.6882924Z   TAG: v24.10.0-beta.5
2024-11-03T08:13:23.6883409Z   PR_TITLE_PREFIX: task: update documentation for
2024-11-03T08:13:23.6883856Z   DOWNSTREAM_REPO_OWNER: nvidia-ci-cd
2024-11-03T08:13:23.6884379Z   DOWNSTREAM_FEATURE_BRANCH: update-docs-for-v24.10.0-beta.5
2024-11-03T08:13:23.6884955Z   UPSTREAM_REPO_OWNER: Mellanox
2024-11-03T08:13:23.6885390Z   UPSTREAM_DEFAULT_BRANCH: main
2024-11-03T08:13:23.6885949Z   COMMIT_MESSAGE: task: update documentation for v24.10.0-beta.5
2024-11-03T08:13:23.6886451Z ##[endgroup]
2024-11-03T08:13:24.1301934Z nvidia-ci-cd/network-operator-docs already …
```

Fixing CI Documentation workflow

---

docs/getting-started-kubernetes.rst
docs/getting-started-openshift.rst

Following example from Network Operator:
https://github.com/Mellanox/network-operator/blob/master/example/crs/mellanox.com_v1alpha1_hostdevicenetwork_cr-ocp.yaml#L20

bug: fix resource name in HostDeviceNetwork

---

.github/workflows/docs-ci.yaml
Makefile

Fixing docs-ci workflow to be triggered upon the following use cases:
1. pull-request (new/modified)
2. tag
3. branch
Examples for propagated workflow env variables:
```
TAG: v1.0-tag-workflow
REF_NAME: v1.0-tag-workflow
REF_HEAD: 
PR_NUMBER: 
PR_TITLE_PREFIX: task: update documentation for
COMMIT_SUFFIX: v1.0-tag-workflow
DOWNSTREAM_REPO_OWNER: nvidia-ci-cd
DOWNSTREAM_FEATURE_BRANCH: update-docs-for-v1.0-tag-workflow
UPSTREAM_REPO_OWNER: Mellanox
UPSTREAM_DEFAULT_BRANCH: main
---
REF_NAME: 5/merge
REF_HEAD: test-pr-workflow
PR_NUMBER: 5
PR_TITLE_PREFIX: task: update documentation for
COMMIT_SUFFIX: pull/5
DOWNSTREAM_REPO_OWNER: nvidia-ci-cd
DOWNSTREAM_FEATURE_BRANCH: update-docs-for-test-pr-workflow
UPSTREAM_REPO_OWNER: Mellanox
UPSTREAM_DEFAULT_BRANCH: main
```

Fixing docs-ci workflow triggers

---

docs/getting-started-kubernetes.rst

chore: Adding DPU mode limitation in `getting-started-kubernetes` doc

chore: Adding DPU mode limitation in getting-started-kubernetes doc

---

docs/getting-started-kubernetes.rst
docs/life-cycle-management.rst

- fix some identation for list
- align style on bash - remove captions

fix: several updates

---

docs/advanced-configurations.rst
docs/platform-support.rst

Prepared documentation and notes for upcoming precompiled DOCA feature.

feat: add precompiled DOCA instructions and notes

---

.github/workflows/docs-ci.yaml

Since custom GH secrets are not propagated for forked repos, we need a way to have GH token to generate docs repo PRs under network-operator repo. 
Solution:
- Use fine grained Github Personal Access Token (PAT), for nvidia-ci-cd user , with limited network-operator-docs permissions
* There is a need to add `GH_DOCS_TOKEN` PAT token for `nvidia-ci-cd` user

chore: Fixing non-propagated custom GH token in forked PRs 

---

.github/workflows/docs-ci.yaml

Caller workflow GH_DOCS_TOKEN secret will be injected as called workflow input instead of inherited secret, since secrets are not implicitly propagated to called workflow

fix: Caller workflow GH_DOCS_TOKEN secret set as input

---

docs/customizations/cr-full-example.rst

Empty config in multus, empty multus config is created causing nodes to be in not ready state.

bug: remove empty config in multus examples

---

.github/workflows/docs-ci.yaml

this change is coupled with the change in network-operator: https://github.com/Mellanox/network-operator/pull/1258

fix: refactor docs ci upstream trigger to operate via workflow_dispatch only

---

docs/platform-support.rst

Updated Platform Support information for v25.4.0

Updating Platform Support info

---

docs/platform-support.rst

Revisited and updated Network Operator Component Matrix with additional details.
Component versions might need to be updated further to reflect the GA release

Revisited and updated Network Operator Component Matrix 

---

docs/getting-started-kubernetes.rst

Otherwise it reads like consecutive instruction steps

fix: add headers to different helm install options

---

docs/getting-started-kubernetes.rst

Changed the wording, sorted the conditions for readability, added a section with updated spec

fix: small improvements to nic op docs

---

docs/nic-conf-operator/nic-configuration-operator.rst
docs/nic-conf-operator/nic-fw-configuration.rst

split the FW upgrade and configuration into separate sections add clarifications

rearrange NIC Configuration Operator docs for better UX
