- docs/overview.rst
source page https://docs.nvidia.com/networking/display/kubernetes2410/nvidia+network+operator
> Add about the network operator page

- docs/advanced-configurations.rst
Source:
https://docs.nvidia.com/networking/display/kubernetes2410/advanced+configurations
Some preview:
> Add advanced configuration page

- docs/common/vars.rst
- docs/getting-started-openshift.rst
Source:
https://docs.nvidia.com/networking/display/kubernetes2410/getting+started+with+red+hat+openshift
> Add Openshift page

- docs/release-notes.rst
Source:
https://docs.nvidia.com/networking/display/kubernetes2410/release+notes
> Add release notes

- docs/platform-support.rst
Signed-off-by: killianmuldoon <cilliancapi@gmail.com>
Fix an issue with how `-` is rendered in the list tables.
> fix: Bullet rendering in table

- docs/platform-support.rst
Signed-off-by: killianmuldoon <cilliancapi@gmail.com>
Fix a broken bullet point in a table. Missed in #26
> fix: broken bullet point in table

- docs/getting-started-kubernetes.rst
The link has been updated in the latest DOCA release
> Update link to OpenvSwithc Offload doc

- docs/getting-started-kubernetes.rst
- docs/getting-started-openshift.rst
clarify that a single instance of NFD is expected in the cluster.
based on: https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/getting-started.html?highlight=nfd#prerequisites
> document nfd prerequisites

- docs/advanced-configurations.rst
- docs/files/entrypoint.sh
- Add steps for MOFED RHCOS precompiled instructions
- Update entrypoint.sh
> Add MOFED RHCOS precompiled instructions

- docs/getting-started-openshift.rst
Remove installPlanApproval field in Subscription
> Fix OCP CLI install

- Makefile
- docs/customizations/helm.rst
- tools/packman/packman
Update Helm docs against network-operator master branch.
> chore: Update helm doc

- .github/workflows/docs-ci.yaml
bugfix triggering from upstream workflow.
> fix: add ci for making docs trigger

- .github/workflows/build.yaml
- .github/workflows/docs-publish.yaml
- .gitignore
- Makefile
- docs/advanced-configurations.rst
- docs/getting-started-kubernetes.rst
- docs/getting-started-openshift.rst
- docs/life-cycle-management.rst
- docs/platform-support.rst
- repo.toml
> bug: add sphinx extension substitutions

- docs/platform-support.rst
Aligning NFD version requirements and installation notes with GPU Operator
> Added a note about NFD version prerequisites

- .github/workflows/docs-ci.yaml
> disable api generation in CI

- docs/release-notes.rst
Additionally this commit also fixes some formatting issues with the previous limitation.
> Add known limitation regarding RHEL and docker to the release notes

- docs/release-notes.rst
update RN for non-supported reset flows in DPU mode
> chore: update RN for non-supported reset flows in DPU mode

- docs/customizations/helm.rst
- templates/helm.rst.gotmpl
> feat: add maintenance operator helm doc

- docs/advanced-configurations.rst
> chore: update doca-driver precompiled

- docs/platform-support.rst
This comment is not related to Nic Feature Discovery
> bug: remove NFD comment

- .github/workflows/docs-ci.yaml
Sign CI commit to comply with DCO check
> bug: Sign CI commit

- docs/customizations/helm.rst
Update variable to be the same as on upstream
> task: sync post-delete variable with upstream

- docs/platform-support.rst
Added Nutanix NKP as part of the support matrix.
> 25.4.0 alexp nutanix
